### ISSUE TITLE
Defaultmode ... missing in persistence configmap

### ISSUE THREAD

**Issue by Whazor** [k8s-at-home/library-charts#117]
After checking [the code](https://github.com/k8s-at-home/library-charts/blob/aa8b14aaf0f58f524f1d50fea5a201dfac30158b/charts/stable/common/templates/lib/controller/_volumes.tpl#L29) I saw that many of the properties that secrets have in persistence are missing in the config map. Whereas the docs say they are there.

**Comment by bjw-s** [comment]
The syntax highlighting is a bit wonky, but the code contains an if/else block that covers the type. The other fields are shared between configmap and secret:
https://github.com/k8s-at-home/library-charts/blob/aa8b14aaf0f58f524f1d50fea5a201dfac30158b/charts/stable/common/templates/lib/controller/_volumes.tpl#L28L34
