### ISSUE TITLE
Allow ignoring nameSuffix for PVC

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/library-charts#13]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

allow having no suffix by giving a negate option

**Anything else you would like to add:**

N/A

**Additional Information:**

Relevant code: 
https://github.com/k8s-at-home/library-charts/blob/a06271207b537e8a5dd4e93f5549905cabaefad3/charts/stable/common/templates/_pvc.tpl#L17-L19

changing L17 to:
```
{{- if or (not $persistenceValues.nameSuffix) (eq $persistenceValues.nameSuffix "-") }}
```

should resolve the issue

**Comment by bjw-s** [comment]
Added this in the upcoming version 👍🏻
