### ISSUE TITLE
Add option for generic Persistent volume claims

### ISSUE THREAD

**Issue by Y0ngg4n** [k8s-at-home/library-charts#134]
# Details

**Helm chart name:** radarr, sonarr, lidarr, nzbget

**Describe the solution you'd like:** For use of Remote Path Mappings there is another persistent volume claim needed. Currently the only option i see is to use the shared volume for it. It would be nice to add a default disabled generic volume in the commons.yaml to make it more flexible to mount other volumes into helm charts.

**Comment by bjw-s** [comment]
Did you check out our docs on the different storage options?

https://docs.k8s-at-home.com/our-helm-charts/common-library-storage

Using the `custom` type you should be able to mount any storage type you need

**Comment by Y0ngg4n** [comment]
@bjw-s yes. but as far as i can understand it i can just add volumes that are already defined and for the radarr chart for example there is only config and media defined and the inherited shared volume. as far as i understand it there is no way to add more volumes.

**Comment by Y0ngg4n** [comment]
Ok sorry i was wrong i thought i could just add volumes that are predefined. but seems like i can just give it a name and it works. Will close it :)
