### ISSUE TITLE
Allow pathTpl

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/library-charts#15]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

pathTpl to match the other tpl options in ingress settings

**Anything else you would like to add:**

N/A

**Additional Information:**

would allow for templating of path based standards. e.g. 
```yaml
pathTpl: '/{{ include "common.names.fullname" . }}'
```

**Comment by bjw-s** [comment]
Closed via #14
