### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by cornfeedhobo** [k8s-at-home/library-charts#152]
This is a simple one. My linter caught it.

https://github.com/k8s-at-home/library-charts/blob/7b56c80a4ee24240456da858969205dd7c46ec6a/charts/stable/common/templates/_notes.tpl#L23

`visting` -> `visiting`

**Comment by bjw-s** [comment]
Thanks for letting us know! I've just pushed a fix to our `development` branch.
