### ISSUE TITLE
[common] I'd like cert-manager Issuer creation and management to be centralized

### ISSUE THREAD

**Issue by cornfeedhobo** [k8s-at-home/library-charts#156]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

I'd like cert-manager `Issuer`s to be created, matching the name of the main service, and optionally used for any service ingress.

**Anything else you would like to add:**

I notice that you have a cluster guide in another repo and it seems to use cert-manager, but I'm not seeing where that would get used and I don't find any documentation for it. It's my understanding that Issuers are scoped to their namespace, thus any service with it's own namespace, which I think is common, would need a dedicated Issuer created.

**Comment by onedr0p** [comment]
Maybe they are namespace scoped? But you can definitely define them globally.

https://github.com/onedr0p/home-ops/blob/main/cluster/core/cert-manager/issuers/letsencrypt-production.yaml

**Comment by cornfeedhobo** [comment]
> If you want to create a single Issuer that can be consumed in multiple namespaces, you should consider creating a ClusterIssuer resource. This is almost identical to the Issuer resource, however is non-namespaced so it can be used to issue Certificates across all namespaces.

[TIL](https://cert-manager.io/docs/concepts/issuer/#namespaces). Thanks for pointing this out.

Hmm, I guess there could still be merits to per-service Issuers, so I'll leave it up to your team to decide if this should be closed. I can see where I'd probably use a ClusterIssuer for most services... :shrug:

**Comment by onedr0p** [comment]
I'm pretty sure a bunch of people do a single ClusterIssuer. I'll go ahead and close this because I don't really see the benefit of having the common chart create issuers.
