### ISSUE TITLE
pathType is not configurable

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/library-charts#16]
# Details

**Helm chart name and version:**

common

**What steps did you take and what happened:**

Tried to configure it, and couldnt

**Relevant Helm values:**

N/A

**What did you expect to happen:**

To be able to configure it.

**Anything else you would like to add:**

N/A

**Additional Information:**

https://github.com/k8s-at-home/library-charts/blob/a06271207b537e8a5dd4e93f5549905cabaefad3/charts/stable/common/templates/classes/_ingress.tpl#L62-L64

L63 should be:
```yaml
pathType: {{ default "Prefix" .pathType }}
```

**Comment by bjw-s** [comment]
Good catch 👍🏻

**Comment by bjw-s** [comment]
Should be fixed with https://github.com/k8s-at-home/library-charts/pull/14/commits/0d7a656b579870a49ff3c2d151842c1bdac55440 when the next library version gets released.
