### ISSUE TITLE
_pvc.yaml in not rendering correctly on some program like ArgoCD

### ISSUE THREAD

**Issue by rolfberkenbosch** [k8s-at-home/library-charts#17]
# Details

**Helm chart name and version:**

The pvc woun't be created because of a bug in the chart. ArgoCD is rendering the json wrong because of a fault in the _pvc.yaml.

**What steps did you take and what happened:**

This is the output:

'''
{
  "---kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "labels": {
      "app.kubernetes.io/instance": "testapp",
      "app.kubernetes.io/managed-by": "Helm",
      "app.kubernetes.io/name": "testapp",
      "app.kubernetes.io/version": "1.0.0",
      "helm.sh/chart": "testapp-0.0.1"
    },
    "name": "testapp-config"
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    }
  }
}
'''

As you can see the '---' is in front of kind.

Be aware that this is not a bug of ArgoCD. If I using the bitnami postgresql with persistence storage. It is generating the correct yaml files for the pvc.

**Comment by onedr0p** [comment]
Please add the chart you are using and the version.

**Comment by onedr0p** [comment]
Whoops sorry I thought this was opened in our charts repo.

**Comment by bjw-s** [comment]
We would need the exact chart values.yaml file to help us reproduce this issue. 

So far I've never come across this in my prd cluster or while developing / debugging charts.

**Comment by DirtyCajunRice** [comment]
That doesnt even look like argocd output. Id say they need
* Output of `argocd version` or screenshot of argocd server version info (modal that pops up when you click the version number under the logo on the top left of the ui)
* Output of `kubectl version`
* Output of `helm version`
* Link to git source of chart that imported common
* Link to entire values.yaml, replacing any sensitive values

**Comment by rolfberkenbosch** [comment]
I try to fix the library-charts myself, I think i found the bug. But i need to setup my own library-chart webpage so that I can test it. But it is really hard with github. I cannot make a fork of this repo and fix it sadly enough :(

**Comment by bjw-s** [comment]
A change has just been pushed to #14 that could _potentially_ be a fix (or better: a workaround).

As for the development flow: you can just check out this repo locally and use the `common-test` chart under the `helper-charts` folder to do local testing with `helm template`. If that renders correctly, I do believe it to be a bug in ArgoCD.

**Comment by rolfberkenbosch** [comment]
> A change has just been pushed to #14 that could _potentially_ be a fix (or better: a workaround).
> 
> As for the development flow: you can just check out this repo locally and use the `common-test` chart under the `helper-charts` folder to do local testing with `helm template`. If that renders correctly, I do believe it to be a bug in ArgoCD.

Sorry, I missed that. Thanks for the tips, I will use that later. Github pages is now working with my fork, and i have tested you change #14. I can confirm that the change will fix the problem in ArgoCD. Thanks for your time @bjw-s !
