### ISSUE TITLE
Deprecate "-" globally

### ISSUE THREAD

**Issue by dirtycajunrice** [k8s-at-home/library-charts#19]
> Nope, the underlying sprig library doesn't differentiate between an empty string and nil (See also https://github.com/Masterminds/sprig/issues/53). Guess we're stuck with `-` for now.

_Originally posted by @bjw-s in https://github.com/k8s-at-home/library-charts/pull/14#discussion_r605862770_

In the same sprig issue, a proper fix was defined: 

> Found a solution `{{ kindIs "invalid" $value }}`

_Originally posted by @jkroepke in https://github.com/Masterminds/sprig/issues/53#issuecomment-483414063_

By changing anything that was `"-"` to a nil value either implicitly or explicitly, you can test for it
```yaml
implicit:
explicit1: nil
explicit2: ~
```

This could not only fix the verbosity concern of `"-"` but additionally allow the common charts that have commented out defaults become uncommented with a nil value to test for existence and optionally requirement

**Comment by bjw-s** [comment]
I couldn't get that `kindIs` fix to work when I tested it, but I may have been doing it wrong 😅 Will try to get it working once more

**Comment by bjw-s** [comment]
```yaml
storageClassName: {{ if (kindIs "invalid" $values.storageClass) }}""{{- else }}{{ $values.storageClass | quote }}{{- end }}
```
If I do this, and provide `storageClass: nil` in the `values.yaml` it won't work. 
I think it might be due to the way the merging of all the Values dicts works. Beginning to suspect that omits any `nil` or empty values.
