### ISSUE TITLE
Set env variables have no effect when value is 0 or false

### ISSUE THREAD

**Issue by ronny35** [k8s-at-home/library-charts#29]
# Details

**Helm chart name and version:**

k8s-at-home: 7.3.1

**What steps did you take and what happened:**

When I apply env.NODE_TLS_REJECT_UNAUTHORIZED = 0 (or false), environnement variable is not deployed

**Relevant Helm values:**

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

**What did you expect to happen:**

Must be present.

**Comment by bjw-s** [comment]
Hi! Thanks for taking the time to raise this issue. The correct way to pass truthy (true/false/1/0, etc) environment variables in Helm charts is by quoting them.

I believe this snippet should work:
```yaml
env:
  NODE_TLS_REJECT_UNAUTHORIZED: "0" # or "false"
```

**Comment by ronny35** [comment]
Hi @bjw-s,

I have the same error.

**Comment by Ornias1993** [comment]
@ronny35 What @bjw-s is trying to tell you:
Env-Vars should always be strings, so need quotes.

He is not saying he has the same error.

**Comment by bjw-s** [comment]
I've added an explicit unit test (https://github.com/k8s-at-home/library-charts/pull/30/commits/3fa4861fd47fe02f72bf98f574c2123b199aa99f) to verify that the quoted "0" works, and it works as expected

**Comment by Ornias1993** [comment]
@bjw-s Can also be closed afaik.

**Comment by bjw-s** [comment]
I am closing this issue for now. If the problem still occurs for you, please don't hesitate to comment again.
