### ISSUE TITLE
v3 Fixes Still needed (list)

### ISSUE THREAD

**Issue by dirtycajunrice** [k8s-at-home/library-charts#49]
Putting this to keep track of stuff I still want to fix before v3.

* hostPathMounts are a good thing but should be merged in with persistence. No need to keep that split
* hostPathMount requires defining both `mountPath` and `hostPath` but you should be able to set one or the other and have it populate the empty one if none set

**Comment by bjw-s** [comment]
Both of these are done, I think all that is needed now is to move the additionalVolume(Mounts) keys to the new `custom` persistence type.
