### ISSUE TITLE
hostmounts (mountPermissions) broken: alpine:3.3 is x64-only, EOL

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/library-charts#54]
https://github.com/k8s-at-home/library-charts/blob/3f3f4a64fb8a9ba7a10362dcea32b4a792ac6abc/charts/stable/common/templates/classes/_mountPermissions.tpl#L47

Changing to alpine:3.6 provides multiple architectures. Alternately, alpine:3 would be further future-proofed.

**Comment by onedr0p** [comment]
We are actually removing this hook in the next version of the library chart. Permissions should be taken care of in other ways.

https://github.com/k8s-at-home/library-charts/commit/160840f3031f942007feb3384e138e3c54cbe42c#diff-0d0dc420d2ecaaefabc9df3b27e62cef581e18da812a93de09d35dca014b7719
