### ISSUE TITLE
Error resolving common.names.fullname with 3.0.0

### ISSUE THREAD

**Issue by roelofjansen** [k8s-at-home/library-charts#57]
# Details

**Helm chart name and version:**

common 3.0.0
blocky 6.4.0

**What steps did you take and what happened:**

I took the blocky chart and updated common to 3.0.0 in Chart.yaml.

I then ran "helm template ."

Error: template: blocky/charts/common/templates/lib/chart/_names.tpl:12:15: executing "common.names.fullname" at <include "common.names.name" .>: error calling include: template: blocky/charts/common/templates/lib/chart/_names.tpl:3:63: executing "common.names.name" at <.Values.global.nameOverride>: nil pointer evaluating interface {}.nameOverride

**Relevant Helm values:**

No changes to the values.yaml  of the blocky chart.

**What did you expect to happen:**

No error since the breaking change was mainly about services and ingresses

**Additional Information:**

Helm v3.5.4

**Comment by bjw-s** [comment]
This will be fixed with #58. Thanks for reporting the issue!

**Comment by bjw-s** [comment]
3.0.1 has been released with the fix 🏅
