### ISSUE TITLE
integrated configmaps

### ISSUE THREAD

**Issue by rwaltr** [k8s-at-home/library-charts#67]
# Details

**Describe the solution you'd like:**

Add configmaps as a integrated commons values, both as an map under Values.configmaps.[0] and Values.persistence.[0]. 

**Anything else you would like to add:**

```yaml
configmaps:
  map1: |
    stuff
    and 
    things
  map22: |
    stuff
    and 
    things

persistance
  map1:
    type:configmap
    configmap: map1
    mountPath: /some/path.txt
  map2:
    type:configmap
    exsistingConfigMap: map2
    mountPath: /some/path.jpeg
  map3:
    type:configmap
    mountPath: /some/path.gif
    config: |
      stuff
      and
      more
```

**Additional Information:**

It "feels" like this could be a modified version of `custom`

**Comment by mfoo** [comment]
This would be great - I use the Home Assistant chart and the most recent version has updated the library chart version. I have a `Volume` and `VolumeMount` configured to allow me to mount a configuration file from a `ConfigMap` but after the update the mounted volume is empty and I've had to roll it back until I have time to figure out the correct configuration. Having a method of doing this that is supported would be super useful.

**Comment by bjw-s** [comment]
Resurrecting this one from the archives... in the upcoming v4.1.0 of the common lib, support for this feature has been added.
