### ISSUE TITLE
Re-add additionalVolumes and additionalVolumeClaims; absence breaks major functionality for power users

### ISSUE THREAD

**Issue by Patricol** [k8s-at-home/library-charts#75]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

I agree the current `persistence` code works very well for most users most of the time; but it seriously breaks things for power users; and the workarounds necessary to make every configuration possible within the confines of `persistence` are IMO nowhere near worth it.

The forced pairing between volumes and volumemounts is fundamentally incompatible with most workarounds that could be made. Separating the concept of a mount and volume is required for a functional solution, but would be unnecessarily confusing for most users.

IMO best solution is just re-adding a way to specify volumes and volumemounts in standard yaml as is common in many other charts.

**Anything else you would like to add:**

`persistence` cannot properly define complex CSI volumes, nor even handle mounting one volume multiple times.

I can whip up a PR if this is received well.

**Comment by Patricol** [comment]
Didn't see #65 ; only searched `additionalVolumes`.

Just read it; I still think this is just as valid.

We do not want to support interpolating every possible parameter for CSI while also providing mechanisms to conditionally exclude assumed-necessary arguments while recreating the conceptual split between volumes and mounts in a user-facing way.

Not when two 3-line escape hatches exist that even match common practices.

**Comment by bjw-s** [comment]
Hi! Thanks for taking the time to write up this issue. 

Specifying complex CSI volumes should very well be possible by using the `custom` persistence type: http://docs.k8s-at-home.com/our-helm-charts/common-library-storage/#custom

Whilst I agree that a small bit of functionality might have potentially been "lost" with the removal of these two keys, I am still curious for any real-world examples you can provide.
