### ISSUE TITLE
Provide functionality to be able to add labels to Deployments

### ISSUE THREAD

**Issue by FrankelJb** [k8s-at-home/library-charts#92]
# Details

**Helm chart name:**

Library Chart Template

library-charts/charts/stable/common/templates/_deployment.tpl 

**Describe the solution you'd like:**

I want to be able to programmatically scale my Deployments across namespaces and without knowing the exact name of every Deployment. I would like to be able to add labels on Deployments and run commands like `kubectl scale deployment -l environment=dev replicas=1`

**Anything else you would like to add:**

No

**Additional Information:**

Seems straightforward enough.

**Comment by bjw-s** [comment]
Hi! 👋 Thanks for raising this issue. The good news is that this functionality is (should) already be in place. 

Check out this section of the values.yaml:
https://github.com/k8s-at-home/library-charts/blob/5a05c6cfae766e271258633cc26408ff7a09f5c9/charts/stable/common/values.yaml#L16

With that you should be able to do what you want.

**Comment by FrankelJb** [comment]
I didn't see it there. I didn't realise the `controller` section was responsible for the deployment type. Thanks for the awesome charts!
